name: macOS

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: macos-latest
    steps:
      - run: curl -o- https://raw.githubusercontent.com/iuiaoin/dotfiles/main/_install/macos.zsh | zsh
